In [3]:
import numpy as np
len_window=10
x_offsets = np.sort(
    np.concatenate((np.arange(-len_window+1, 1, 1),))
)
print(x_offsets)
print(abs(min(x_offsets)) )

[-9 -8 -7 -6 -5 -4 -3 -2 -1  0]
9


In [6]:
import torch
import torch.nn as nn
a = torch.randn(1,3,4)
mp = nn.MaxPool2d(2,stride=2)
output = mp(a)
print(output.shape)

torch.Size([1, 1, 2])


In [2]:
len_window=10
x_offsets = np.sort(
    (np.arange(-len_window+1, 1, 1),)
)
print(x_offsets)

[[-9 -8 -7 -6 -5 -4 -3 -2 -1  0]]


In [2]:
import torch
print(torch.cuda.device_count())
print(torch.cuda.get_device_name(0))

1
NVIDIA GeForce RTX 3080 Ti Laptop GPU


In [17]:
import numpy as np
import torch
import torch.nn as nn
criterion = nn.MSELoss()
observations = np.linspace(0,10,10).reshape(2,5)
target = np.linspace(0,10,10).reshape(2,5)
print(observations.shape)
print(target.shape)

#observations = torch.tensor(observations)
#target = torch.tensor(target)

print(type(observations))
print(type(target))
loss_num = criterion(observations,target)
print(loss_den)

a = observations.mean().expand(observations.shape)
print(a.shape)

print(type(observations))
print(type(a))
loss_den = criterion(observations,a)
print(loss_den)

loss = loss_num / loss_den
print(loss)

(2, 5)
(2, 5)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


TypeError: 'int' object is not callable

In [5]:
from sklearn.metrics import confusion_matrix
import numpy as np
y_true = np.array([1,1,1,1])
y_pred_class = np.array([1,2,2,1])
cm = confusion_matrix(y_true, y_pred_class)
print(cm)

[[2 2]
 [0 0]]


In [7]:
from sklearn.metrics import f1_score
import numpy as np
y_true = np.array([1,2,2,3,4,1,2,3,1])
y_pred_class = np.array([1,2,2,3,4,2,2,3,1])
# param 'average' is required for multiclass/multilabel targets.
# If None, the scores for each class are returned.
# https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html
f1 = f1_score(y_true, y_pred_class, average=None)
# ps:
# the shape of f1-score depends on this:
# no matter what shape y_true has, it will be automatically detected that how many labels are mentioned
# and the number of labels equals to the shape of output of f1-score
# if there is extra labels in y_pred, shape of f1-score will accordingly add
# e.g.
# current y_true has shape [9,] but only 4 labels appear(e.g.1,2,3,4)
# then f1.score will have shape [4,]
print(f1,f1.shape)

[0.8        0.85714286 1.         1.        ] (4,)


In [10]:
from sklearn.metrics import recall_score
import numpy as np
y_true = np.array([1,2,2,3,4,1,2,3,1])
y_pred_class = np.array([1,2,2,3,2,2,2,3,1])
recall = recall_score(y_true, y_pred_class, average=None)
# explanation of shape is the same with fi-score
print(recall,recall.shape)

[0.66666667 1.         1.         0.        ] (4,)


In [35]:
from sklearn.metrics import r2_score
import numpy as np
y_true = np.array([1,2,2,3,4,1,2,3,1])
y_pred_class = np.array([1,2,1,2,4,1,1,4,1])
r2 = r2_score(y_true, y_pred_class)
print(recall,recall.shape)
r2 = r2_score(y_pred_class, y_true)
print(recall,recall.shape)

[1.         0.33333333 0.         1.        ] (4,)
[1.         0.33333333 0.         1.        ] (4,)


In [39]:
import numpy as np
target = np.array([1,2,2,3,4,1,2,3,1])
prediction = np.array([1,2,1,2,4,1,1,4,1])
whatever = (np.abs(prediction- target) > 0.33333)
summation = np.sum(np.abs(prediction- target) > 0.33333)
print(whatever)
print(summation)

[False False  True  True False False  True  True False]
4


In [2]:
import json
 
# Data to be written
dictionary = {
    "ber": 0.0004,
    "mae": 0.23,
    "gpu": "cuda0",
}
 
with open("watever.json", "w") as outfile:
    json.dump(dictionary, outfile)

In [54]:
import json
import os
import torch
import numpy
# dict1 = {'11':1, '22':2, '33':3}
a = torch.Tensor([3])
print(type(a))
dict1 = {11:a, 22:2, 33:3}
print(type(dict1))
dict_out = {}
for key,value in dict1.items():
    if isinstance(value, torch.Tensor):
        value = value.tolist()[0]
    dict_out[key] = value
path = os.path.join('./record',"output.json")
with open(path, "a") as outfile:
    json.dump(dict_out, outfile)
print(dict_out)

<class 'torch.Tensor'>
<class 'dict'>
{11: 3.0, 22: 2, 33: 3}


In [68]:
a = 11
dd = {a:1, 22:2, 33:3}
d = {key:value for key,value in dd.items()}
d['dd'] = 9
print(type(d))
print(d['asd'])

<class 'dict'>


KeyError: 'asd'

In [82]:
import pandas as pd
import os

path = 'data.csv'

asd = 0
sdf = 1
columns_lst = ['asd', 'sdf']

if not os.path.exists(path):
    df = pd.DataFrame(None,columns=columns_lst)
    df.to_csv(path,index=False)

df1 = pd.DataFrame([["0.0fasw3","0.933"]], columns=columns_lst)
df1.to_csv(path,index=False,header=False,mode='a')

In [88]:
# delete last row of csv file
path = 'data.csv'
df = pd.read_csv(path)
print(df, type(df))
print()
df1 = df.iloc[:2]
df2 = df.iloc[3:]
df3 = pd.concat([df1,df2])
print(df3)
print()

for i,d in enumerate(df.iterrows()):
    print(type(d[1]['asd']))

        asd    sdf
0  0.0fasw3  0.933
1  0.0fasw3  0.933
2  0.0fasw3  0.933
3  0.0fasw3  0.933
4  0.0fasw3  0.933 <class 'pandas.core.frame.DataFrame'>

        asd    sdf
0  0.0fasw3  0.933
1  0.0fasw3  0.933
3  0.0fasw3  0.933
4  0.0fasw3  0.933

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [64]:
# find a specific line
path = 'data.csv'
df = pd.read_csv(path)
print(df)
df1 = pd.DataFrame([["0.023","0.933"]], columns=columns_lst)
df = pd.concat([df,df1])
print(df)
df.to_csv(path,index=False)

   Unnamed: 0       asd    sdf
0         new  0.0fasw3  0.933
1         old  0.0fasw3  0.933
2         new  0.0fasw3  0.933
3         old  0.0fasw3  0.933
4         new  0.0fasw3  0.933
5         old  0.0fasw3  0.933
6    bilibili  0.0fasw3  0.933
7          qq  0.0fasw3  0.933
8         new  0.0fasw3  0.933
9         old  0.0fasw3  0.933
10   bilibili  0.0fasw3  0.933
11         qq  0.0fasw3  0.933
12        NaN     0.023  0.933
13        NaN     0.023  0.933
   Unnamed: 0       asd    sdf
0         new  0.0fasw3  0.933
1         old  0.0fasw3  0.933
2         new  0.0fasw3  0.933
3         old  0.0fasw3  0.933
4         new  0.0fasw3  0.933
5         old  0.0fasw3  0.933
6    bilibili  0.0fasw3  0.933
7          qq  0.0fasw3  0.933
8         new  0.0fasw3  0.933
9         old  0.0fasw3  0.933
10   bilibili  0.0fasw3  0.933
11         qq  0.0fasw3  0.933
12        NaN     0.023  0.933
13        NaN     0.023  0.933
0         NaN     0.023  0.933


In [73]:
# delete last row of csv file
path = 'data.csv'
df = pd.read_csv(path)
print(df)
df = df.iloc[:-1]
print(df)
df.to_csv(path,index=False)

     asd    sdf
0  0.002  0.998
1  0.002  0.998
2  0.002  0.998
     asd    sdf
0  0.002  0.998
1  0.002  0.998


In [116]:
# find a specific line
path = 'data.csv'
df = pd.read_csv(path)
print(type(df))
print(df.empty)

df = df['asd'].iloc[:-1]
print(df == False)

<class 'pandas.core.frame.DataFrame'>
False
0    False
Name: asd, dtype: bool


In [12]:
import pandas as pd
# find a specific line
path = 'data.csv'
df = pd.read_csv(path, index_col ="asd")
# print(df)
print(df.loc['0.0qw3'])


sdf    0.933
Name: 0.0qw3, dtype: float64


In [52]:
a = [12]
b = {11:a, 22:2, 33:3}
bb = list(k for k in b)
print(a+bb)

[12, 11, 22, 33]


In [120]:
a = {1:2,2:3}
b = {4:5,7:6}
a.update(b)
print(a)

{1: 2, 2: 3, 4: 5, 7: 6}


In [4]:
import numpy as np
import torch
import torch.nn as nn
# inp = torch.randint(0,20,(1,3,4))
inp = torch.randn(2,18)
print(inp)
maxP = nn.MaxPool1d(kernel_size=3,stride=2,padding=1)
out = maxP(inp)
print(out,out.shape)

tensor([[-0.8557,  2.9463,  1.3732,  0.8265, -1.2170, -1.7125, -1.3309,  0.9196,
          0.6638, -1.2524, -1.6385,  0.6368, -1.2392, -0.8258, -0.4717, -1.4345,
          1.6966,  0.5838],
        [-1.1421,  0.3442,  0.4735,  1.3267, -0.3638,  1.4131,  1.3017, -0.5808,
          0.7761, -1.0341,  0.5279, -0.6067, -0.4592, -1.6457, -0.4595, -1.0897,
         -0.4757, -0.2247]])
tensor([[ 2.9463,  2.9463,  0.8265,  0.9196,  0.9196,  0.6368,  0.6368, -0.4717,
          1.6966],
        [ 0.3442,  1.3267,  1.4131,  1.4131,  0.7761,  0.5279, -0.4592, -0.4595,
         -0.2247]]) torch.Size([2, 9])


In [5]:
a = [1,2,2,4]
print(sum(a))

9


In [3]:
dict_ss = {1:11,2:22,3:33}
for (i,j) in dict_ss.items():
    print(i,j)

1 11
2 22
3 33


In [17]:
dd = dict(abs_rel=1, rmse=2, rmse_log=3,sq_rel=4, torch_rmse=5, mape=6, r2=7)
aa = (v for k,v in dd.items())
print("{abs_rel:5.4f} {rmse} {rmse_log} {sq_rel} {torch_rmse} {mape} {r2}".format(**dd))

1.0000 2 3 4 5 6 7


In [5]:
import numpy as np
import torch
a = np.arange(1,13,1)
print(a)
a = np.arange(1,13,1).reshape(3,4)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
b = np.array([[
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
]])
print(b.shape)
b = b.reshape(1,-1)
print(b, b.shape)

(1, 3, 4)
[[1 1 1 1 2 2 2 2 3 3 3 3]] (1, 12)
