### Math Operation

In [1]:
import torch

#### Basic

In [21]:
a = torch.randint(0,10,(3,2))
b = torch.full([2],2)
# addition
print('addition: ')
# take addition as example:
# broadcasting of torch.tensor is similar with numpy.array
# i.e. lower-dim tensor broadcasts to higher-dim tensor along with the hightest dimension
# e.g. a.shape=(3,2), b.shape=(2,), broadcasting works
# however, if a.shape=(3,2), b.shape=(3,), broadcasting doesn't work
print(a)
print(b)
print(a+b)
print('a+b == torch.add(a,b): ', torch.all(torch.eq(a+b,torch.add(a,b))))
print('----------------------------------------------------------')
# substraction
print('substraction: ')
print('a-b == torch.sub(a,b): ', torch.all(torch.eq(a-b,torch.sub(a,b))))
print('----------------------------------------------------------')
# elementary multiplication
# attention: this is different from matrix multiplication
print('elementary multiplication: ')
print('a*b == torch.mul(a,b): ', torch.all(torch.eq(a*b,torch.mul(a,b))))
print((a*b).shape)
print('----------------------------------------------------------')
# division
print('division: ')
print('a/b == torch.div(a,b): ', torch.all(torch.eq(a/b,torch.div(a,b))))
print('----------------------------------------------------------')

addition: 
tensor([[1, 6],
        [6, 3],
        [4, 3]])
tensor([2, 2])
tensor([[3, 8],
        [8, 5],
        [6, 5]])
a+b == torch.add(a,b):  tensor(True)
----------------------------------------------------------
substraction: 
a-b == torch.sub(a,b):  tensor(True)
----------------------------------------------------------
elementary multiplication: 
a*b == torch.mul(a,b):  tensor(True)
torch.Size([3, 2])
----------------------------------------------------------
division: 
a/b == torch.div(a,b):  tensor(True)
----------------------------------------------------------


#### Matrix Multiplication

In [91]:
a = torch.full([2,3],2.)
print('a: ')
print(a, a.shape, a.type())
b = torch.ones(3)
print('b: ')
print(b, b.shape, b.type())
# datatypes of multipliers must be same
print('a@b == torch.matmul(a,b): ', torch.all(torch.eq(a@b,torch.matmul(a,b))))

'''example of dimension decreasing'''
print('-------------------------------------------------------------------------')
# flatten a dataset with 4 pictures, 3 channels, 28x28 pixels into [4,784]
# decrease dimesnion through layer1 from [4,748] to [4,512]
inp = torch.randn(4,784)
print('inp shape: ', inp.shape)
# in convention of Pytorch, weight should have shpe of:[channel_out,channel_in]
# and take transpose when applied
weight = torch.randn(512,784)
output = inp@weight.t()
print('inp @ weight.t(): ', output.shape)

'''multiple matrix-multiplication in parallel'''
print('-------------------------------------------------------------------------')
# only last 2 dimensions will excute matrix multiplication
pic_batch = torch.randn([4,3,32,28])
layer = torch.randn([4,3,28,14])
output = torch.matmul(pic_batch,layer)
print('pic_batch @ layer: ', output.shape)

a: 
tensor([[2., 2., 2.],
        [2., 2., 2.]]) torch.Size([2, 3]) torch.FloatTensor
b: 
tensor([1., 1., 1.]) torch.Size([3]) torch.FloatTensor
a@b == torch.matmul(a,b):  tensor(True)
-------------------------------------------------------------------------
inp shape:  torch.Size([4, 784])
inp @ weight.t():  torch.Size([4, 512])
-------------------------------------------------------------------------
pic_batch @ layer:  torch.Size([4, 3, 32, 14])


#### dimension details of matrix multiplications

In [94]:
c = torch.rand(3)
d = torch.rand(2,3)

# c.shape: [3]
# d.shape: [2,3]
# if c x d: [3] x [2,3], c must be automatically reshape as [smth,2], which is impossible
# so c x d doesn't work
# if d x c: [2,3] x [3], c can be considered as vertical vector,
# so the result is [2], which has same dimension with c
print('c: ', c.shape)
print('d: ', d.shape)
print('d x c: ', torch.matmul(d,c).shape)
print('--------------------------------------------')

# transpose of 1D tensor is the same as itself
# the rule is also the same with previous situation
print('c.t()==c: ', torch.all(c.t()==c))
print('c.t(): ', (c.t()).shape)
print('d: ', d.shape)
print('d x c.t(): ', torch.matmul(d,c.T).shape)
print('--------------------------------------------')

# if c x d.T: [3] x [3,2], c can be considered as horizontal vector,
# so the result is also [2], which has same dimension with c
# if d.T x c: [3,2] x [3], c must be automatically reshape as [2,smth], which is impossible
# so d.T x c doesn't work
print('c: ', c.shape)
print('d.T: ', (d.T).shape)
print('c x d.T: ', torch.matmul(c, d.T).shape)
print('--------------------------------------------')

# if reshape c as [3,1] or [1,3], the situation will be same with normal matrix multiplication
# and pay attention to corresponding dimenions
c = c.reshape(3,1)
print('c: ', c.shape)
print('d: ', d.shape)
print('d x c: ', torch.matmul(d,c).shape)
print('--------------------------------------------')

c = c.reshape(1,3)
print('c: ', c.shape)
print('d.T: ', (d.T).shape)
print('c x d.T: ', torch.matmul(c,d.T).shape)

c:  torch.Size([3])
d:  torch.Size([2, 3])
d x c:  torch.Size([2])
--------------------------------------------
c.t()==c:  tensor(True)
c.t():  torch.Size([3])
d:  torch.Size([2, 3])
d x c.t():  torch.Size([2])
--------------------------------------------
c:  torch.Size([3])
d.T:  torch.Size([3, 2])
c x d.T:  torch.Size([2])
--------------------------------------------
c:  torch.Size([3, 1])
d:  torch.Size([2, 3])
d x c:  torch.Size([2, 1])
--------------------------------------------
c:  torch.Size([1, 3])
d.T:  torch.Size([3, 2])
c x d.T:  torch.Size([1, 2])


#### Power

In [40]:
a = torch.full([2,2],4)
print(a)
print(a**2)
print(a.pow(2))
print(torch.pow(a,2))
print(pow(a,2))
print(a.sqrt())
print(a**(0.5))

tensor([[4, 4],
        [4, 4]])
tensor([[16, 16],
        [16, 16]])
tensor([[16, 16],
        [16, 16]])
tensor([[16, 16],
        [16, 16]])
tensor([[16, 16],
        [16, 16]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.]])


#### Exp and Log

In [100]:
a = torch.ones(2,2)
e = torch.exp(a)
print('e: ', e)
# torch.log() takes 'e' as basis defaultly
log_e = torch.log(e)
print('log_e', log_e)
# torch.log10() takes 10 as basis, and so on
log_10 = torch.log10(e)
print('log_10', log_10)

e:  tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])
log_e tensor([[1., 1.],
        [1., 1.]])
log_10 tensor([[0.4343, 0.4343],
        [0.4343, 0.4343]])


#### Approximation

In [101]:
a = torch.tensor(3.4)
# .floor():  take upper integer
# .ceil():   take lower integer
# .trunc():  take integer part
# .frac():   take fraction part
print(a.floor(),a.ceil(),a.trunc(),a.frac())
# 四舍五入
print(torch.tensor(3.5).round())
print(torch.tensor(3.49).round())

tensor(3.) tensor(4.) tensor(3.) tensor(0.4000)
tensor(4.)
tensor(3.)


#### Clamp

In [103]:
# e.g. gradient clamping
grad = torch.randn(2,3)*15
print(grad)
# input: .clamp(min)
# replace all elements less than 'min' with 'min'
# others remain
clmp1 = grad.clamp(5)
print(clmp1)
# input: .clamp(min,max)
# replace all elements less than 'min' with 'min'
#                      greater than 'max' with 'max'
# others remain
clmp1 = grad.clamp(0,20)
print(clmp1)

tensor([[  2.9546, -29.4667, -22.4124],
        [  8.9374,   1.9090,  -0.4860]])
tensor([[5.0000, 5.0000, 5.0000],
        [8.9374, 5.0000, 5.0000]])
tensor([[2.9546, 0.0000, 0.0000],
        [8.9374, 1.9090, 0.0000]])
