### Statistics

In [1]:
import torch

#### Norm

<font size = 2>
    
1-Norm:
    
$$Norm_1 = \sum |x|$$
    
2-Norm:
    
$$Norm_1 = \sqrt{\sum |x|^{2}}$$

In [9]:
# input: array.norm(n-norm,dim)
#        n-norm: designated norm, 1 or 2
#        dim:    along which dimension to compute norm
Norm_0 = torch.full([8],1.)
Norm_1 = a.reshape(2,4)
Norm_2 = a.reshape(2,2,2)
Norm_lst = [Norm_0,Norm_1,Norm_2]

for n in Norm_lst:
    print('array:',n)
    print('1-norm is:', n.norm(1))
    print('2-norm is:', n.norm(2))
    if n.dim() != 1:
        print('1-norm along dim0 is:', n.norm(1,dim = 0))
        print('2-norm along dim0 is:', n.norm(2,dim = 0))
    print('-----------------------------------------------------------')

array: tensor([1., 1., 1., 1., 1., 1., 1., 1.])
1-norm is: tensor(8.)
2-norm is: tensor(2.8284)
-----------------------------------------------------------
array: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
1-norm is: tensor(8.)
2-norm is: tensor(2.8284)
1-norm along dim0 is: tensor([2., 2., 2., 2.])
2-norm along dim0 is: tensor([1.4142, 1.4142, 1.4142, 1.4142])
-----------------------------------------------------------
array: tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
1-norm is: tensor(8.)
2-norm is: tensor(2.8284)
1-norm along dim0 is: tensor([[2., 2.],
        [2., 2.]])
2-norm along dim0 is: tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])
-----------------------------------------------------------


#### Basic Statistic Attributes

In [9]:
a = torch.randn(4,5)
print(a)
print('==========================================================')
# a.max() defaultly 'flattens' the array and take max
print('a.max():',a.max())
print('a.min():', a.min())
# a.max(dim) takes max along designated dim,return values and indices
print('a.max(dim=0):',a.max(dim=1))
# and the returned result can be indexed
print(a.max(dim=1)[0])
print(a.max(dim=1)[1])
print('a.min(dim=0):',a.min(dim=0))
# input: keepdim
# if keepdim = True, then remain original dimension
print('a.max(dim=0, keepdim = True):',a.max(dim=1, keepdim = True))
print('a.min(dim=0, keepdim = True):',a.min(dim=0, keepdim = True))
print('----------------------------------------------------------')
# a.mean():  average
# a.prod():  accumulated product
# the situations are similar with max()/min()
# return flattened results without 'dim'
print(a.sum(),a.mean(),a.prod())
print('----------------------------------------------------------')
# defaultly, the array is flattened into dim 1 and return corresponding index
# a.argmax(): the index of a.max()
# a.argmin(): the index of a.min()
print(a.argmax(),a.argmin())
# find index of max or min along a specific dim
print(a.argmax(dim = 0),a.argmin(dim = 1))

tensor([[-0.5557, -0.3938,  0.6927, -2.1592,  0.0805],
        [ 0.3270,  0.2820,  0.1577, -1.2370, -1.2399],
        [ 0.2043, -1.0154,  0.2553,  0.0894,  1.4474],
        [-0.4010,  0.2939, -0.2611,  0.2104, -0.3992]])
a.max(): tensor(1.4474)
a.min(): tensor(-2.1592)
a.max(dim=0): torch.return_types.max(
values=tensor([0.6927, 0.3270, 1.4474, 0.2939]),
indices=tensor([2, 0, 4, 1]))
tensor([0.6927, 0.3270, 1.4474, 0.2939])
tensor([2, 0, 4, 1])
a.min(dim=0): torch.return_types.min(
values=tensor([-0.5557, -1.0154, -0.2611, -2.1592, -1.2399]),
indices=tensor([0, 2, 3, 0, 1]))
a.max(dim=0, keepdim = True): torch.return_types.max(
values=tensor([[0.6927],
        [0.3270],
        [1.4474],
        [0.2939]]),
indices=tensor([[2],
        [0],
        [4],
        [1]]))
a.min(dim=0, keepdim = True): torch.return_types.min(
values=tensor([[-0.5557, -1.0154, -0.2611, -2.1592, -1.2399]]),
indices=tensor([[0, 2, 3, 0, 1]]))
----------------------------------------------------------
tensor(-3

#### topk & kthvalue

In [12]:
# give a scene:
# predict each picture show which single number
# 4 pictures with 10 values which show respectively possibilities to be that number
pred = torch.randn(4,10)
# wanted: the most 3 possible (most 3 max) predicted number
# the return contains values and indices, which can be indexed
print(pred.topk(3,dim=1))
print(pred.topk(3,dim=1)[0])
print('=====================================================')
# wanted: the most 3 impossible (most 3 min) predicted number
print(pred.topk(3,dim=1,largest=False))
print('=====================================================')
# wanted: the 4th impossible number
# attention: .kthvalue() only return results from lowest value, and cannot be inverse
# e.g. the 8th smallest is exactly the 3rd largest
print(pred.kthvalue(8,dim=1))

torch.return_types.topk(
values=tensor([[ 1.1670,  0.2394,  0.1880],
        [ 1.2879,  0.5098,  0.2336],
        [ 2.1438,  2.1025,  0.7517],
        [ 1.4081, -0.0622, -0.1390]]),
indices=tensor([[3, 5, 7],
        [3, 6, 1],
        [7, 2, 1],
        [3, 0, 4]]))
tensor([[ 1.1670,  0.2394,  0.1880],
        [ 1.2879,  0.5098,  0.2336],
        [ 2.1438,  2.1025,  0.7517],
        [ 1.4081, -0.0622, -0.1390]])
torch.return_types.topk(
values=tensor([[-2.3198, -0.7830, -0.6400],
        [-1.9828, -1.6678, -0.8083],
        [-1.3674, -0.7456,  0.3508],
        [-1.8039, -1.4360, -1.3084]]),
indices=tensor([[0, 8, 2],
        [4, 9, 5],
        [3, 0, 5],
        [2, 7, 8]]))
torch.return_types.kthvalue(
values=tensor([ 0.1880,  0.2336,  0.7517, -0.1390]),
indices=tensor([7, 1, 1, 4]))


#### Comparison

In [15]:
a = torch.randint(0,4,(3,3))
b = torch.randint(0,4,(3,3))
print(a)
print(b)
print('==========================================')
# possible operators:
#    ==, >=, <=, !=, >, <
print(a==b)
print(a>2)
print('==========================================')
# compare if equal
#   torch.eq() compare elementary values
print(torch.eq(a,b))
#   torch.eq() compare the whole array
print(torch.equal(a,b))
print(torch.all(torch.eq(a,b)))

tensor([[1, 2, 0],
        [3, 3, 1],
        [3, 3, 0]])
tensor([[0, 3, 2],
        [0, 1, 1],
        [3, 1, 1]])
tensor([[False, False, False],
        [False, False,  True],
        [ True, False, False]])
tensor([[False, False, False],
        [ True,  True, False],
        [ True,  True, False]])
tensor([[False, False, False],
        [False, False,  True],
        [ True, False, False]])
False
tensor(False)
